services:
  - type: web
    name: theophilus-chatbot-api
    env: python
    startCommand: gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 90
    plan: free
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: web-portfolio
      - key: PINECONE_NAMESPACE
        value: portfolio-knowledge
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-gcp
      - key: WEB_APP_URL
        value: https://theoincodeland-portfolio.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        value: dpdira4rd
      - key: CLOUDINARY_API_KEY
        value: "462776747915157"
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false